'use client'

import { useCallback, useEffect, useState } from 'react'
import LawyerTestHeader from '@/components/LawyerTestHeader'
import { ApiMessage, apiError } from '@/components/LawyerTestState'
import { lawyerCaseAPI, lawyerDocumentsAPI } from '@/lib/api'

type Summary = { case_id: string; case_number: string; current_stage?: string | null; executive_summary: string; key_facts: Array<{ text?: string }>; bns_sections: Array<{ section_number?: string; title?: string | null }>; timeline_preview: Array<{ id: string; date: string; title: string; description: string }> }
export default function SummaryPage() {
  const [caseId, setCaseId] = useState<string | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [text, setText] = useState(''); const [stage, setStage] = useState(''); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [options, setOptions] = useState({ include_executive_summary: true, include_timeline: true, include_key_facts: true, include_bns_sections: true, include_original_documents: true })
  const load = useCallback(async (id: string) => { setLoading(true); setError(''); try { const r = await lawyerCaseAPI.getSummary(id); setSummary(r.data); setText(r.data.executive_summary || ''); setStage(r.data.current_stage || '') } catch (e) { setError(apiError(e, 'Could not load case summary.')) } finally { setLoading(false) } }, [])
  useEffect(() => { lawyerDocumentsAPI.workspace().then(r => { setCaseId(r.data.id); return load(r.data.id) }).catch(e => { setError(apiError(e, 'Could not load your case workspace.')); setLoading(false) }) }, [load])
  async function save() { if (!caseId) return; setWorking(true); setError(''); setSuccess(''); try { const r = await lawyerCaseAPI.saveSummary(caseId, { executive_summary: text, current_stage: stage || null }); setSummary(r.data); setSuccess('Summary saved.') } catch (e) { setError(apiError(e, 'Could not save summary.')) } finally { setWorking(false) } }
  async function exportPackage() { if (!caseId) return; setWorking(true); setError(''); setSuccess(''); try { const r = await lawyerCaseAPI.export(caseId, options); const url = URL.createObjectURL(new Blob([r.data], { type: 'application/pdf' })); const a = document.createElement('a'); a.href = url; a.download = `case-package-${caseId}.pdf`; a.click(); URL.revokeObjectURL(url); setSuccess('PDF package generated and downloaded.') } catch (e) { setError(apiError(e, 'Could not generate the PDF package.')) } finally { setWorking(false) } }
  return <main className="min-h-screen bg-[#f7f4ec] px-4 py-7"><div className="mx-auto max-w-6xl"><LawyerTestHeader title="Case Summary & Export" caseId={caseId} /><ApiMessage error={error} success={success} />{loading ? <p>Loading summary…</p> : <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-[#ded5c1] bg-white p-5"><h2 className="font-serif text-xl font-bold text-[#0f305b]">Persistent case summary</h2><p className="mt-1 text-sm text-slate-600">Case number: {summary?.case_number}</p><label className="mt-4 block text-sm font-medium">Current stage<input value={stage} onChange={e => setStage(e.target.value)} placeholder="e.g. Review" className="mt-1 w-full rounded border p-2" /></label><label className="mt-4 block text-sm font-medium">Executive summary<textarea value={text} onChange={e => setText(e.target.value)} placeholder="Write a lawyer-reviewed summary…" className="mt-1 min-h-48 w-full rounded border p-2" /></label><div className="mt-3 flex gap-2"><button onClick={save} disabled={working} className="rounded-lg bg-[#c28b19] px-4 py-2 font-semibold text-white disabled:opacity-50">Save summary</button><button onClick={() => caseId && load(caseId)} className="rounded-lg border px-4 py-2">Refresh</button></div></section>
    <section className="rounded-xl border border-[#ded5c1] bg-white p-5"><h2 className="font-serif text-xl font-bold text-[#0f305b]">Export case package</h2><p className="mt-1 text-sm text-slate-600">The backend returns the actual PDF response.</p><div className="mt-4 space-y-2">{Object.entries(options).map(([key, checked]) => <label key={key} className="flex gap-2 text-sm"><input type="checkbox" checked={checked} onChange={e => setOptions({ ...options, [key]: e.target.checked })} />{key.replace('include_', '').replaceAll('_', ' ')}</label>)}</div><button onClick={exportPackage} disabled={working} className="mt-5 rounded-lg bg-[#0f305b] px-4 py-2 font-semibold text-white disabled:opacity-50">{working ? 'Generating…' : 'Generate & download PDF'}</button></section>
    <section className="rounded-xl border border-[#ded5c1] bg-white p-5"><h2 className="font-serif text-xl font-bold text-[#0f305b]">Timeline preview</h2>{summary?.timeline_preview.length ? <ul className="mt-3 space-y-3">{summary.timeline_preview.map(e => <li key={e.id}><p className="font-semibold">{e.date} — {e.title}</p><p className="text-sm text-slate-600">{e.description}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No timeline events are saved.</p>}</section>
    <section className="rounded-xl border border-[#ded5c1] bg-white p-5"><h2 className="font-serif text-xl font-bold text-[#0f305b]">Facts and BNS sections</h2><h3 className="mt-3 text-sm font-bold uppercase text-slate-500">Key facts</h3>{summary?.key_facts.length ? <ul className="mt-1 list-disc pl-5 text-sm">{summary.key_facts.map((f, i) => <li key={i}>{f.text || 'Not mentioned'}</li>)}</ul> : <p className="text-sm text-slate-500">None extracted.</p>}<h3 className="mt-4 text-sm font-bold uppercase text-slate-500">Potential BNS sections</h3>{summary?.bns_sections.length ? <ul className="mt-1 list-disc pl-5 text-sm">{summary.bns_sections.map((s, i) => <li key={i}>Section {s.section_number}{s.title ? ` — ${s.title}` : ''}</li>)}</ul> : <p className="text-sm text-slate-500">None extracted.</p>}</section></div>}</div></main>
}
