"""Add complaint_text to FIRRegistry

Revision ID: e130ed9b43c2
Revises: 90a587e01cc4
Create Date: 2026-09-06 15:40:44.681032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e130ed9b43c2'
down_revision: Union[str, Sequence[str], None] = '90a587e01cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fir_registry', sa.Column('complaint_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fir_registry', 'complaint_text')
    # ### end Alembic commands ###
