'use client'

import { useCallback, useEffect, useState } from 'react'
import LawyerTestHeader from '@/components/LawyerTestHeader'
import { ApiMessage, apiError } from '@/components/LawyerTestState'
import { lawyerCaseAPI, lawyerDocumentsAPI } from '@/lib/api'

type Event = { id: string; date: string; time?: string | null; title: string; description: string; event_type: string; source_document_name?: string | null; source_document_id?: string | null; is_edited?: boolean }
const types = ['Incident', 'Police Complaint', 'FIR', 'Medical', 'Witness Statement', 'Investigation', 'Charge Sheet', 'Court Proceedings']
export default function TimelinePage() {
  const [caseId, setCaseId] = useState<string | null>(null); const [events, setEvents] = useState<Event[]>([]); const [selected, setSelected] = useState<Event | null>(null); const [dateFrom, setDateFrom] = useState(''); const [dateTo, setDateTo] = useState(''); const [eventType, setEventType] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const load = useCallback(async (id: string, filters = true) => { setLoading(true); setError(''); try { const r = await lawyerCaseAPI.getTimeline(id, filters ? { event_type: eventType || undefined, date_from: dateFrom || undefined, date_to: dateTo || undefined } : undefined); setEvents(r.data); setSelected((current) => r.data.find((e: Event) => e.id === current?.id) || null) } catch (e) { setError(apiError(e, 'Could not load timeline.')) } finally { setLoading(false) } }, [dateFrom, dateTo, eventType])
  useEffect(() => { lawyerDocumentsAPI.workspace().then((r) => { setCaseId(r.data.id); return load(r.data.id, false) }).catch((e) => { setError(apiError(e, 'Could not load your case workspace.')); setLoading(false) }) }, [load])
  async function save() { if (!caseId || !selected) return; setError(''); setSuccess(''); try { const r = await lawyerCaseAPI.updateTimeline(caseId, selected.id, { date: selected.date, time: selected.time || null, title: selected.title, description: selected.description, event_type: selected.event_type }); setSelected(r.data); setSuccess('Timeline event saved.'); await load(caseId) } catch (e) { setError(apiError(e, 'Could not save timeline event.')) } }
  return <main className="min-h-screen bg-[#f7f4ec] px-4 py-7"><div className="mx-auto max-w-6xl"><LawyerTestHeader title="Case Timeline" caseId={caseId} /><ApiMessage error={error} success={success} /><section className="mb-5 rounded-xl border border-[#ded5c1] bg-white p-4"><div className="flex flex-wrap items-end gap-3"><label className="text-sm">From<input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} className="mt-1 block rounded border p-2" /></label><label className="text-sm">To<input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} className="mt-1 block rounded border p-2" /></label><label className="text-sm">Type<select value={eventType} onChange={e => setEventType(e.target.value)} className="mt-1 block rounded border p-2"><option value="">All types</option>{types.map(t => <option key={t}>{t}</option>)}</select></label><button onClick={() => caseId && load(caseId)} className="rounded-lg bg-[#0f305b] px-4 py-2 font-semibold text-white">Apply / refresh</button><button onClick={() => { setDateFrom(''); setDateTo(''); setEventType(''); caseId && load(caseId, false) }} className="rounded-lg border px-4 py-2">Clear</button></div></section>
    <div className="grid gap-5 lg:grid-cols-[1fr_0.85fr]"><section className="space-y-3">{loading ? <p>Loading timeline…</p> : events.length === 0 ? <div className="rounded-xl border border-dashed bg-white p-8 text-center">No events match these filters. Run analysis after documents are parsed.</div> : events.map(e => <button key={e.id} onClick={() => setSelected(e)} className={`block w-full rounded-xl border p-4 text-left ${selected?.id === e.id ? 'border-[#c28b19] bg-amber-50' : 'border-[#ded5c1] bg-white'}`}><p className="font-bold text-[#0f305b]">{e.date}{e.time ? ` · ${e.time}` : ''} — {e.title}</p><p className="mt-1 text-sm text-slate-600">{e.event_type} · {e.source_document_name || 'No source document'}</p><p className="mt-2 line-clamp-2 text-sm">{e.description}</p></button>)}</section>
      <section className="h-fit rounded-xl border border-[#ded5c1] bg-white p-5">{!selected ? <p className="text-slate-600">Select an event to inspect or edit it.</p> : <><h2 className="font-serif text-xl font-bold text-[#0f305b]">Event details</h2><div className="mt-4 space-y-3"><label className="block text-sm">Date<input type="date" value={selected.date} onChange={e => setSelected({ ...selected, date: e.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Time<input value={selected.time || ''} onChange={e => setSelected({ ...selected, time: e.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Title<input value={selected.title} onChange={e => setSelected({ ...selected, title: e.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Type<select value={selected.event_type} onChange={e => setSelected({ ...selected, event_type: e.target.value })} className="mt-1 w-full rounded border p-2">{types.map(t => <option key={t}>{t}</option>)}</select></label><label className="block text-sm">Description<textarea value={selected.description} onChange={e => setSelected({ ...selected, description: e.target.value })} className="mt-1 min-h-32 w-full rounded border p-2" /></label><p className="text-xs text-slate-500">Source: {selected.source_document_name || 'Not available'} (read-only)</p><button onClick={save} className="rounded-lg bg-[#c28b19] px-4 py-2 font-semibold text-white">Save event</button></div></>}</section></div></div></main>
}
